# Generated by Django 3.1.6 on 2023-09-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_Date',
            new_name='published_date',
        ),
    ]
